/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicaempleado20240611;

import Entidades.Empleado;
import Utilerias.OpcionesCRUD;
import static Utilerias.OpcionesCRUD.CREAR;
import static Utilerias.OpcionesCRUD.ELIMINAR;
import static Utilerias.OpcionesCRUD.MODIFICAR;
import accesoadatos.EmpleadoDAL;
import javax.swing.JOptionPane;

/**
 *
 * @author MINEDUCYT
 */
public class FrmEmpleadoEsc extends javax.swing.JFrame {

    private OpcionesCRUD opcionCRUD;
    private Empleado empleadoActual = new Empleado();

    /**
     * Creates new form FrmEmpleadoEsc
     */
    public FrmEmpleadoEsc(OpcionesCRUD opcion, Empleado empleado) {
        this.opcionCRUD = opcion;
        initComponents();

        if (opcion != OpcionesCRUD.CREAR) {
            asignarDatos(empleado);
            empleadoActual = empleado;
        }
    }

    private void asignarDatos(Empleado empleado) {
        jTextNombreEmpleado.setText(empleado.getNombre());
        jTextApelidoEmpleado.setText(empleado.getApellido());
        jTextCargo.setText(empleado.getCargo());
        jTextSalario.setText(String.valueOf(empleado.getSalario()));
    }

    private Empleado obtenerDatos() {
        Empleado empleado = new Empleado();
        empleado.setNombre(jTextNombreEmpleado.getText());
        empleado.setApellido(jTextApelidoEmpleado.getText());
        empleado.setCargo(jTextCargo.getText());
        empleado.setSalario(Double.parseDouble(jTextSalario.getText()));

        if (empleadoActual != null) {
            empleado.setEmpleadoId(empleadoActual.getEmpleadoId());
        }

        return empleado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextApelidoEmpleado = new javax.swing.JTextField();
        jTextNombreEmpleado = new javax.swing.JTextField();
        jTextCargo = new javax.swing.JTextField();
        jTextSalario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Cargo");

        jLabel4.setText("Salario");

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jBtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombreEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jTextApelidoEmpleado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTextSalario))
                            .addComponent(jTextCargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApelidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
          if (null != opcionCRUD) {
            switch (opcionCRUD) {
                case CREAR:
                    crearEmpleado();
                    JOptionPane.showMessageDialog(this, "Se Añadió el Registro", "Crear", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case MODIFICAR:
                    modificarEmpleado();
                    JOptionPane.showMessageDialog(this, "Se Modificó el Registro", "Modificar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case ELIMINAR:
                    eliminarEmpleado();
                    JOptionPane.showMessageDialog(this, "Se Eliminó el Registro", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
     private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
    }

    private void crearEmpleado() {
        try {
            Empleado empleado = obtenerDatos();
            EmpleadoDAL.insertar(empleado);
            JOptionPane.showMessageDialog(this,
                    "El empleado fue registrado exitosamente", "CREAR EMPLEADO",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void modificarEmpleado() {
        try {
            Empleado empleado = obtenerDatos();
            EmpleadoDAL.actualizar(empleado);
            JOptionPane.showMessageDialog(this,
                    "El empleado fue modificado exitosamente", "MODIFICAR EMPLEADO",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR EMPLEADO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminarEmpleado() {
        try {
            Empleado empleado = obtenerDatos();
            EmpleadoDAL.eliminar(empleado.getEmpleadoId());
            JOptionPane.showMessageDialog(this,
                    "El empleado fue eliminado exitosamente", "ELIMINAR EMPLEADO",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR EMPLEADO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextApelidoEmpleado;
    private javax.swing.JTextField jTextCargo;
    private javax.swing.JTextField jTextNombreEmpleado;
    private javax.swing.JTextField jTextSalario;
    // End of variables declaration//GEN-END:variables
}
