/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicaempleado20240611;

import Entidades.Empleado;
import Entidades.Vacacion;
import Utilerias.OpcionesCRUD;
import accesoadatos.VacacionDAL;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINEDUCYT
 */
public class FrmGestionVacacionesLec extends javax.swing.JFrame {

    private OpcionesCRUD opcionCRUD;

    /**
     * Creates new form FrmGestionVacacionesLec
     */
    public FrmGestionVacacionesLec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jScrollEmpleado = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnIrACrear = new javax.swing.JButton();

        setTitle("Lector de Gestion de Vaciones");

        jLabel1.setText("Empleado:");

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "VacacioneID", "EmpleadoID", "Nombre", "Apellido", "Cargo", "Salario", "FechaInicio", "FechaFin", "Motivo"
            }
        ));
        jScrollEmpleado.setViewportView(jTableEmpleados);

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnIrACrear.setText("Ir A Crear");
        jBtnIrACrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIrACrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnEditar)
                                .addGap(81, 81, 81)
                                .addComponent(jBtnEliminar)
                                .addGap(83, 83, 83)
                                .addComponent(jBtnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnIrACrear)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jBtnIrACrear))
                .addGap(18, 18, 18)
                .addComponent(jScrollEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnEliminar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIrACrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIrACrearActionPerformed
        // TODO add your handling code here:
        opcionCRUD = OpcionesCRUD.CREAR;
        FrmVacacionesEsc frmVacacionesEsc = new FrmVacacionesEsc(opcionCRUD, new vacacion());
        frmVacacionesEsc.setTitle("Crear Vacación");
        frmVacacionesEsc.setVisible(true);
    }//GEN-LAST:event_jBtnIrACrearActionPerformed


    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private Vacacion obtenerDatos() {
        Vacacion vacacion = new Vacacion();
        int row = jTableVacaciones.getSelectedRow();
        vacacion.setVacacionID((int) jTableVacaciones.getValueAt(row, 0));
        vacacion.setFechaInicio((LocalDate) jTableVacaciones.getValueAt(row, 1));
        vacacion.setFechaFin((LocalDate) jTableVacaciones.getValueAt(row, 2));
        vacacion.setMotivo(jTableVacaciones.getValueAt(row, 3).toString());
        
        Empleado empleado = new Empleado();
        empleado.setEmpleadoId((int) jTableVacaciones.getValueAt(row, 4));
        empleado.setNombre(jTableVacaciones.getValueAt(row, 5).toString());
        vacacion.setEmpleado(empleado);
        
        return vacacion;
    }

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        int row = jTableVacaciones.getSelectedRow();
        if (row != -1) {
            opcionCRUD = OpcionesCRUD.MODIFICAR;
            FrmVacacionesEsc frmVacacionesEsc = new FrmVacacionesEsc(opcionCRUD, obtenerDatos());
            frmVacacionesEsc.setTitle("Modificar vacación");
            frmVacacionesEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "Vacación",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed


    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
         int row = jTableVacaciones.getSelectedRow();
        if (row != -1) {
            opcionCRUD = OpcionesCRUD.ELIMINAR;
            FrmVacacionesEsc frmVacacionesEsc = new FrmVacacionesEsc(opcionCRUD, obtenerDatos());
            frmVacacionesEsc.setTitle("Eliminar vacación");
            frmVacacionesEsc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "Vacación",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // TODO add your handling code here:
        Empleado empleadoSearch = new Empleado();
        empleadoSearch.setNombre(jTxtNombreEmpleado.getText());
        ArrayList<Vacacion> vacaciones = VacacionDAL.buscar(new Vacacion(empleadoSearch));
        String[] columnas = {"VacacionID", "FechaInicio", "FechaFin", "Motivo", "EmpleadoID", "Nombre Empleado"};
        Object[][] datos = new Object[vacaciones.size()][6];
        for (int i = 0; i < vacaciones.size(); i++) {
            Vacacion vacacion = vacaciones.get(i);
            datos[i][0] = vacacion.getVacacionID();
            datos[i][1] = vacacion.getFechaInicio();
            datos[i][2] = vacacion.getFechaFin();
            datos[i][3] = vacacion.getMotivo();
            datos[i][4] = vacacion.getEmpleado().getEmpleadoId();
            datos[i][5] = vacacion.getEmpleado().getNombre();
        }
        DefaultTableModel modelTable = new DefaultTableModel(datos, columnas);
        jTableVacaciones.setModel(modelTable);
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnIrACrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollEmpleado;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
