/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicaempleado20240611;

import Entidades.Empleado;
import Entidades.Vacacion;
import Utilerias.OpcionesCRUD;
import javax.swing.JOptionPane;
import accesoadatos.EmpleadoDAL;
import accesoadatos.VacacionDAL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author MINEDUCYT
 */

public class FrmVacacionesEsc extends javax.swing.JFrame {

    private OpcionesCRUD opcionCRUD;
    private Vacacion vacacionActual = new Vacacion();
    private ArrayList<Empleado> empleados;


    /**
     * Creates new form FrmVacacionesEsc
     */
 public FrmVacacionesEsc(OpcionesCRUD opcion, Vacacion vacacion) {
    this.opcionCRUD = opcion;
    initComponents();
    
    empleados = EmpleadoDAL.obtenerTodos();
        DefaultComboBoxModel<Empleado> modelEmpleados = new DefaultComboBoxModel(empleados.toArray());
        jComboEmpleadoID.setModel(modelEmpleados);
        
    
    if (opcion != OpcionesCRUD.CREAR) {
        asignarDatos(vacacion);
        vacacionActual = vacacion;
    }
}
    private void asignarDatos(Vacacion vacacion) {
        Empleado empleado = vacacion.getEmpleado();
        jTextFechaInicio.setText(vacacion.getFechaInicio().format(DateTimeFormatter.ISO_DATE));
        jTextFechaFin.setText(vacacion.getFechaFin().format(DateTimeFormatter.ISO_DATE));
        jTxtMotivo.setText(vacacion.getMotivo());
        jComboEmpleadoID.setSelectedItem(empleado); // Establecer el empleado seleccionado en el combo box
    }

    private Vacacion obtenerDatos() throws ParseException {
        Vacacion vacacion = new Vacacion();

        Empleado empleado = (Empleado) jComboEmpleadoID.getSelectedItem(); // Obtener el empleado seleccionado del combo box
        vacacion.setEmpleado(empleado);

        // Convertir la fechaInicio al formato adecuado para la base de datos
        String fechaInicioTexto = jTextFechaInicio.getText().trim();
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date parsedFechaInicio = formatoEntrada.parse(fechaInicioTexto);
        SimpleDateFormat formatoSalida = new SimpleDateFormat("yyyy-MM-dd");
        String formattedFechaInicio = formatoSalida.format(parsedFechaInicio);
        vacacion.setFechaInicio(LocalDate.parse(formattedFechaInicio));

        // Convertir la fechaFin al formato adecuado para la base de datos
        String fechaFinTexto = jTextFechaFin.getText().trim();
        java.util.Date parsedFechaFin = formatoEntrada.parse(fechaFinTexto);
        String formattedFechaFin = formatoSalida.format(parsedFechaFin);
        vacacion.setFechaFin(LocalDate.parse(formattedFechaFin));
        vacacion.setMotivo(jTxtMotivo.getText());
        if (vacacionActual != null) {
            vacacion.setVacacionID(vacacionActual.getVacacionID());
        }
        return vacacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtMotivo = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTextFechaInicio = new javax.swing.JTextField();
        jTextFechaFin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboEmpleadoID = new javax.swing.JComboBox<>();

        setTitle("Modificador de Gestion de Vaciones");

        jLabel5.setText("Fecha Inicio");

        jLabel6.setText("Fecha Fin");

        jLabel7.setText("Motivo");

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("EmpoleadoID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBtnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jBtnCancelar)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboEmpleadoID, 0, 150, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jTextFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jTextFechaInicio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnGuardar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        if (null != opcionCRUD) {
            switch (opcionCRUD) {
                case CREAR:
                    crearVacacion();
                    JOptionPane.showMessageDialog(this, "Se Añadio el Registro", "Crear", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case MODIFICAR:
                    modificarVacacion();
                    JOptionPane.showMessageDialog(this, "Se Modifico El Registro", "Modificar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case ELIMINAR:
                    eliminarVacacion();
                    JOptionPane.showMessageDialog(this, "Se Elimino el Registro", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        }
    }


    private void crearVacacion() {
    try {
        Vacacion vacacion = obtenerDatos();
        int result = VacacionDAL.crear(vacacion);
        if (result > 0) {
            JOptionPane.showMessageDialog(this,
                    "La vacación fue registrada exitosamente", "CREAR VACACIÓN",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al crear la vacación", "ERROR VACACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void modificarVacacion() {
    try {
        Vacacion vacacion = obtenerDatos();
        int result = VacacionDAL.modificar(vacacion);
        if (result > 0) {
            JOptionPane.showMessageDialog(this,
                    "La vacación fue modificada exitosamente", "MODIFICAR VACACIÓN",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al modificar la vacación", "ERROR VACACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), "ERROR VACACIÓN",
                JOptionPane.ERROR_MESSAGE);
    }
}


    private void eliminarVacacion() {
    try {
        Vacacion vacacion = obtenerDatos();
        int result = VacacionDAL.eliminar(vacacion);
        if (result > 0) {
            JOptionPane.showMessageDialog(this,
                    "La vacación fue eliminada exitosamente", "ELIMINAR VACACIÓN",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al eliminar la vacación", "ERROR VACACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), "ERROR VACACIÓN",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<Empleado> jComboEmpleadoID;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFechaFin;
    private javax.swing.JTextField jTextFechaInicio;
    private javax.swing.JTextField jTxtMotivo;
    // End of variables declaration//GEN-END:variables
}
