/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicaempleado20240611;

import Entidades.Empleado;
import Entidades.Vacacion;
import Utilerias.OpcionesCRUD;
import javax.swing.JOptionPane;
import accesoadatos.EmpleadoDAL;
import accesoadatos.VacacionDAL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author MINEDUCYT
 */
public class FrmVacacionesEsc extends javax.swing.JFrame {

    private OpcionesCRUD opcionCRUD;
    private Vacacion vacacionActual = new Vacacion();
    private ArrayList<Empleado> empleados;

    /**
     * Creates new form FrmVacacionesEsc
     */
    public FrmVacacionesEsc(OpcionesCRUD opcion, Vacacion vacacion) {
        this.opcionCRUD = opcion;
        initComponents();
        empleados = EmpleadoDAL.obtenerTodos();

        if (opcion != OpcionesCRUD.CREAR) {
            asignarDatos(vacacion);
            vacacionActual = vacacion;
        }
    }

    private void asignarDatos(Vacacion vacacion) {
        Empleado empleado = vacacion.getEmpleado();
    jTxtNombre.setText(empleado.getNombre());
    jTextApellido.setText(empleado.getApellido());
    jTxtCargo.setText(empleado.getCargo());
    jTxtSalario.setText(String.valueOf(empleado.getSalario()));
    jTextFechaInicio.setText(vacacion.getFechaInicio().format(DateTimeFormatter.ISO_DATE));
    jTextFechaFin.setText(vacacion.getFechaFin().format(DateTimeFormatter.ISO_DATE));
    jTxtMotivo.setText(vacacion.getMotivo());
    }

    private Vacacion obtenerDatos() {
       Vacacion vacacion = new Vacacion();
    
    Empleado empleado = new Empleado();
    empleado.setNombre(jTxtNombre.getText());
    empleado.setApellido(jTextApellido.getText());
    empleado.setCargo(jTxtCargo.getText());
    empleado.setSalario(Double.parseDouble(jTxtSalario.getText()));
    
    vacacion.setEmpleado(empleado);

   String fechaInicioTexto = jTextFechaInicio.getText().trim();
    String fechaFinTexto = jTextFechaFin.getText().trim();

    LocalDate fechaInicio = null;
    LocalDate fechaFin = null;

    if (!fechaInicioTexto.isEmpty()) {
        if (fechaInicioTexto.matches("\\d{4}-\\d{2}-\\d{2}")) {
            fechaInicio = LocalDate.parse(fechaInicioTexto, DateTimeFormatter.ISO_DATE);
            vacacion.setFechaInicio(fechaInicio);
        } else {
            // Mostrar mensaje de error al usuario indicando que el formato de fecha es incorrecto
            JOptionPane.showMessageDialog(this, "El formato de fecha de inicio debe ser YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    if (!fechaFinTexto.isEmpty()) {
        if (fechaFinTexto.matches("\\d{4}-\\d{2}-\\d{2}")) {
            fechaFin = LocalDate.parse(fechaFinTexto, DateTimeFormatter.ISO_DATE);
            vacacion.setFechaFin(fechaFin);
        } else {
            // Mostrar mensaje de error al usuario indicando que el formato de fecha es incorrecto
            JOptionPane.showMessageDialog(this, "El formato de fecha de fin debe ser YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    vacacion.setMotivo(jTxtMotivo.getText());
    if (vacacionActual != null) {
        vacacion.setVacacionID(vacacionActual.getVacacionID());
    }
    return vacacion;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtMotivo = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTextFechaInicio = new javax.swing.JTextField();
        jTextFechaFin = new javax.swing.JTextField();

        setTitle("Modificador de Gestion de Vaciones");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Cargo");

        jLabel4.setText("Salario");

        jLabel5.setText("Fecha Inicio");

        jLabel6.setText("Fecha Fin");

        jLabel7.setText("Motivo");

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCargo)
                            .addComponent(jTextFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jTextFechaInicio)
                            .addComponent(jTxtSalario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBtnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jBtnCancelar)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnGuardar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        if (null != opcionCRUD) {
            switch (opcionCRUD) {
                case CREAR:
                    crearVacacion();
                    JOptionPane.showMessageDialog(this, "Se Añadio el Registro", "Crear", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case MODIFICAR:
                    modificarVacacion();
                    JOptionPane.showMessageDialog(this, "Se Modifico El Registro", "Modificar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                case ELIMINAR:
                    eliminarVacacion();
                    JOptionPane.showMessageDialog(this, "Se Elimino el Registro", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        }
    }

    private void crearVacacion() {
       try {
            Vacacion vacacion = obtenerDatos();
            int result = VacacionDAL.crear(vacacion);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "La vacación fue registrada exitosamente", "CREAR VACACIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al crear la vacación", "ERROR VACACIÓN",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void modificarVacacion() {
    try {
        Vacacion vacacion = obtenerDatos();
        int result = VacacionDAL.modificar(vacacion);
        if (result > 0) {
            JOptionPane.showMessageDialog(this,
                    "La vacación fue modificada exitosamente", "MODIFICAR VACACIÓN",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al modificar la vacación", "ERROR VACACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(), "ERROR VACACIÓN",
                JOptionPane.ERROR_MESSAGE);
    }
}


    private void eliminarVacacion() {
        try {
            Vacacion vacacion = obtenerDatos();
            int result = VacacionDAL.eliminar(vacacion);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "La vacación fue eliminada exitosamente", "ELIMINAR VACACIÓN",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al eliminar la vacación", "ERROR VACACIÓN",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR VACACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextFechaFin;
    private javax.swing.JTextField jTextFechaInicio;
    private javax.swing.JTextField jTxtCargo;
    private javax.swing.JTextField jTxtMotivo;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
